// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package learnProto.selfTest;

public final class MyTest {
  private MyTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 uint32 = 1;</code>
     */
    int getUint32();

    /**
     * <code>uint64 uint64 = 2;</code>
     */
    long getUint64();

    /**
     * <code>int32 int32 = 3;</code>
     */
    int getInt32();

    /**
     * <code>int64 int64 = 4;</code>
     */
    long getInt64();

    /**
     * <code>sint32 sint32 = 5;</code>
     */
    int getSint32();

    /**
     * <code>sint64 sint64 = 6;</code>
     */
    long getSint64();

    /**
     * <code>fixed32 fixed32 = 7;</code>
     */
    int getFixed32();

    /**
     * <code>fixed64 fixed64 = 8;</code>
     */
    long getFixed64();

    /**
     * <code>bool bool = 9;</code>
     */
    boolean getBool();

    /**
     * <code>string str = 10;</code>
     */
    java.lang.String getStr();
    /**
     * <code>string str = 10;</code>
     */
    com.google.protobuf.ByteString
        getStrBytes();

    /**
     * <code>float float = 11;</code>
     */
    float getFloat();

    /**
     * <code>double double = 12;</code>
     */
    double getDouble();

    /**
     * <code>.google.protobuf.Timestamp time = 13;</code>
     */
    boolean hasTime();
    /**
     * <code>.google.protobuf.Timestamp time = 13;</code>
     */
    com.google.protobuf.Timestamp getTime();
    /**
     * <code>.google.protobuf.Timestamp time = 13;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();
  }
  /**
   * Protobuf type {@code Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Data)
      DataOrBuilder {
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
      uint32_ = 0;
      uint64_ = 0L;
      int32_ = 0;
      int64_ = 0L;
      sint32_ = 0;
      sint64_ = 0L;
      fixed32_ = 0;
      fixed64_ = 0L;
      bool_ = false;
      str_ = "";
      float_ = 0F;
      double_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              uint32_ = input.readUInt32();
              break;
            }
            case 16: {

              uint64_ = input.readUInt64();
              break;
            }
            case 24: {

              int32_ = input.readInt32();
              break;
            }
            case 32: {

              int64_ = input.readInt64();
              break;
            }
            case 40: {

              sint32_ = input.readSInt32();
              break;
            }
            case 48: {

              sint64_ = input.readSInt64();
              break;
            }
            case 61: {

              fixed32_ = input.readFixed32();
              break;
            }
            case 65: {

              fixed64_ = input.readFixed64();
              break;
            }
            case 72: {

              bool_ = input.readBool();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              str_ = s;
              break;
            }
            case 93: {

              float_ = input.readFloat();
              break;
            }
            case 97: {

              double_ = input.readDouble();
              break;
            }
            case 106: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (time_ != null) {
                subBuilder = time_.toBuilder();
              }
              time_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(time_);
                time_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return learnProto.selfTest.MyTest.internal_static_Data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return learnProto.selfTest.MyTest.internal_static_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              learnProto.selfTest.MyTest.Data.class, learnProto.selfTest.MyTest.Data.Builder.class);
    }

    public static final int UINT32_FIELD_NUMBER = 1;
    private int uint32_;
    /**
     * <code>uint32 uint32 = 1;</code>
     */
    public int getUint32() {
      return uint32_;
    }

    public static final int UINT64_FIELD_NUMBER = 2;
    private long uint64_;
    /**
     * <code>uint64 uint64 = 2;</code>
     */
    public long getUint64() {
      return uint64_;
    }

    public static final int INT32_FIELD_NUMBER = 3;
    private int int32_;
    /**
     * <code>int32 int32 = 3;</code>
     */
    public int getInt32() {
      return int32_;
    }

    public static final int INT64_FIELD_NUMBER = 4;
    private long int64_;
    /**
     * <code>int64 int64 = 4;</code>
     */
    public long getInt64() {
      return int64_;
    }

    public static final int SINT32_FIELD_NUMBER = 5;
    private int sint32_;
    /**
     * <code>sint32 sint32 = 5;</code>
     */
    public int getSint32() {
      return sint32_;
    }

    public static final int SINT64_FIELD_NUMBER = 6;
    private long sint64_;
    /**
     * <code>sint64 sint64 = 6;</code>
     */
    public long getSint64() {
      return sint64_;
    }

    public static final int FIXED32_FIELD_NUMBER = 7;
    private int fixed32_;
    /**
     * <code>fixed32 fixed32 = 7;</code>
     */
    public int getFixed32() {
      return fixed32_;
    }

    public static final int FIXED64_FIELD_NUMBER = 8;
    private long fixed64_;
    /**
     * <code>fixed64 fixed64 = 8;</code>
     */
    public long getFixed64() {
      return fixed64_;
    }

    public static final int BOOL_FIELD_NUMBER = 9;
    private boolean bool_;
    /**
     * <code>bool bool = 9;</code>
     */
    public boolean getBool() {
      return bool_;
    }

    public static final int STR_FIELD_NUMBER = 10;
    private volatile java.lang.Object str_;
    /**
     * <code>string str = 10;</code>
     */
    public java.lang.String getStr() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        str_ = s;
        return s;
      }
    }
    /**
     * <code>string str = 10;</code>
     */
    public com.google.protobuf.ByteString
        getStrBytes() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLOAT_FIELD_NUMBER = 11;
    private float float_;
    /**
     * <code>float float = 11;</code>
     */
    public float getFloat() {
      return float_;
    }

    public static final int DOUBLE_FIELD_NUMBER = 12;
    private double double_;
    /**
     * <code>double double = 12;</code>
     */
    public double getDouble() {
      return double_;
    }

    public static final int TIME_FIELD_NUMBER = 13;
    private com.google.protobuf.Timestamp time_;
    /**
     * <code>.google.protobuf.Timestamp time = 13;</code>
     */
    public boolean hasTime() {
      return time_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 13;</code>
     */
    public com.google.protobuf.Timestamp getTime() {
      return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
    }
    /**
     * <code>.google.protobuf.Timestamp time = 13;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
      return getTime();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uint32_ != 0) {
        output.writeUInt32(1, uint32_);
      }
      if (uint64_ != 0L) {
        output.writeUInt64(2, uint64_);
      }
      if (int32_ != 0) {
        output.writeInt32(3, int32_);
      }
      if (int64_ != 0L) {
        output.writeInt64(4, int64_);
      }
      if (sint32_ != 0) {
        output.writeSInt32(5, sint32_);
      }
      if (sint64_ != 0L) {
        output.writeSInt64(6, sint64_);
      }
      if (fixed32_ != 0) {
        output.writeFixed32(7, fixed32_);
      }
      if (fixed64_ != 0L) {
        output.writeFixed64(8, fixed64_);
      }
      if (bool_ != false) {
        output.writeBool(9, bool_);
      }
      if (!getStrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, str_);
      }
      if (float_ != 0F) {
        output.writeFloat(11, float_);
      }
      if (double_ != 0D) {
        output.writeDouble(12, double_);
      }
      if (time_ != null) {
        output.writeMessage(13, getTime());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uint32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, uint32_);
      }
      if (uint64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, uint64_);
      }
      if (int32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, int32_);
      }
      if (int64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, int64_);
      }
      if (sint32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(5, sint32_);
      }
      if (sint64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(6, sint64_);
      }
      if (fixed32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(7, fixed32_);
      }
      if (fixed64_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(8, fixed64_);
      }
      if (bool_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, bool_);
      }
      if (!getStrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, str_);
      }
      if (float_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(11, float_);
      }
      if (double_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(12, double_);
      }
      if (time_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, getTime());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof learnProto.selfTest.MyTest.Data)) {
        return super.equals(obj);
      }
      learnProto.selfTest.MyTest.Data other = (learnProto.selfTest.MyTest.Data) obj;

      boolean result = true;
      result = result && (getUint32()
          == other.getUint32());
      result = result && (getUint64()
          == other.getUint64());
      result = result && (getInt32()
          == other.getInt32());
      result = result && (getInt64()
          == other.getInt64());
      result = result && (getSint32()
          == other.getSint32());
      result = result && (getSint64()
          == other.getSint64());
      result = result && (getFixed32()
          == other.getFixed32());
      result = result && (getFixed64()
          == other.getFixed64());
      result = result && (getBool()
          == other.getBool());
      result = result && getStr()
          .equals(other.getStr());
      result = result && (
          java.lang.Float.floatToIntBits(getFloat())
          == java.lang.Float.floatToIntBits(
              other.getFloat()));
      result = result && (
          java.lang.Double.doubleToLongBits(getDouble())
          == java.lang.Double.doubleToLongBits(
              other.getDouble()));
      result = result && (hasTime() == other.hasTime());
      if (hasTime()) {
        result = result && getTime()
            .equals(other.getTime());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UINT32_FIELD_NUMBER;
      hash = (53 * hash) + getUint32();
      hash = (37 * hash) + UINT64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUint64());
      hash = (37 * hash) + INT32_FIELD_NUMBER;
      hash = (53 * hash) + getInt32();
      hash = (37 * hash) + INT64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInt64());
      hash = (37 * hash) + SINT32_FIELD_NUMBER;
      hash = (53 * hash) + getSint32();
      hash = (37 * hash) + SINT64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSint64());
      hash = (37 * hash) + FIXED32_FIELD_NUMBER;
      hash = (53 * hash) + getFixed32();
      hash = (37 * hash) + FIXED64_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFixed64());
      hash = (37 * hash) + BOOL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBool());
      hash = (37 * hash) + STR_FIELD_NUMBER;
      hash = (53 * hash) + getStr().hashCode();
      hash = (37 * hash) + FLOAT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getFloat());
      hash = (37 * hash) + DOUBLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDouble()));
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static learnProto.selfTest.MyTest.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static learnProto.selfTest.MyTest.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static learnProto.selfTest.MyTest.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static learnProto.selfTest.MyTest.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static learnProto.selfTest.MyTest.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static learnProto.selfTest.MyTest.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static learnProto.selfTest.MyTest.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static learnProto.selfTest.MyTest.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static learnProto.selfTest.MyTest.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static learnProto.selfTest.MyTest.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static learnProto.selfTest.MyTest.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static learnProto.selfTest.MyTest.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(learnProto.selfTest.MyTest.Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Data)
        learnProto.selfTest.MyTest.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return learnProto.selfTest.MyTest.internal_static_Data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return learnProto.selfTest.MyTest.internal_static_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                learnProto.selfTest.MyTest.Data.class, learnProto.selfTest.MyTest.Data.Builder.class);
      }

      // Construct using learnProto.selfTest.MyTest.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uint32_ = 0;

        uint64_ = 0L;

        int32_ = 0;

        int64_ = 0L;

        sint32_ = 0;

        sint64_ = 0L;

        fixed32_ = 0;

        fixed64_ = 0L;

        bool_ = false;

        str_ = "";

        float_ = 0F;

        double_ = 0D;

        if (timeBuilder_ == null) {
          time_ = null;
        } else {
          time_ = null;
          timeBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return learnProto.selfTest.MyTest.internal_static_Data_descriptor;
      }

      public learnProto.selfTest.MyTest.Data getDefaultInstanceForType() {
        return learnProto.selfTest.MyTest.Data.getDefaultInstance();
      }

      public learnProto.selfTest.MyTest.Data build() {
        learnProto.selfTest.MyTest.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public learnProto.selfTest.MyTest.Data buildPartial() {
        learnProto.selfTest.MyTest.Data result = new learnProto.selfTest.MyTest.Data(this);
        result.uint32_ = uint32_;
        result.uint64_ = uint64_;
        result.int32_ = int32_;
        result.int64_ = int64_;
        result.sint32_ = sint32_;
        result.sint64_ = sint64_;
        result.fixed32_ = fixed32_;
        result.fixed64_ = fixed64_;
        result.bool_ = bool_;
        result.str_ = str_;
        result.float_ = float_;
        result.double_ = double_;
        if (timeBuilder_ == null) {
          result.time_ = time_;
        } else {
          result.time_ = timeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof learnProto.selfTest.MyTest.Data) {
          return mergeFrom((learnProto.selfTest.MyTest.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(learnProto.selfTest.MyTest.Data other) {
        if (other == learnProto.selfTest.MyTest.Data.getDefaultInstance()) return this;
        if (other.getUint32() != 0) {
          setUint32(other.getUint32());
        }
        if (other.getUint64() != 0L) {
          setUint64(other.getUint64());
        }
        if (other.getInt32() != 0) {
          setInt32(other.getInt32());
        }
        if (other.getInt64() != 0L) {
          setInt64(other.getInt64());
        }
        if (other.getSint32() != 0) {
          setSint32(other.getSint32());
        }
        if (other.getSint64() != 0L) {
          setSint64(other.getSint64());
        }
        if (other.getFixed32() != 0) {
          setFixed32(other.getFixed32());
        }
        if (other.getFixed64() != 0L) {
          setFixed64(other.getFixed64());
        }
        if (other.getBool() != false) {
          setBool(other.getBool());
        }
        if (!other.getStr().isEmpty()) {
          str_ = other.str_;
          onChanged();
        }
        if (other.getFloat() != 0F) {
          setFloat(other.getFloat());
        }
        if (other.getDouble() != 0D) {
          setDouble(other.getDouble());
        }
        if (other.hasTime()) {
          mergeTime(other.getTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        learnProto.selfTest.MyTest.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (learnProto.selfTest.MyTest.Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int uint32_ ;
      /**
       * <code>uint32 uint32 = 1;</code>
       */
      public int getUint32() {
        return uint32_;
      }
      /**
       * <code>uint32 uint32 = 1;</code>
       */
      public Builder setUint32(int value) {
        
        uint32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 uint32 = 1;</code>
       */
      public Builder clearUint32() {
        
        uint32_ = 0;
        onChanged();
        return this;
      }

      private long uint64_ ;
      /**
       * <code>uint64 uint64 = 2;</code>
       */
      public long getUint64() {
        return uint64_;
      }
      /**
       * <code>uint64 uint64 = 2;</code>
       */
      public Builder setUint64(long value) {
        
        uint64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 uint64 = 2;</code>
       */
      public Builder clearUint64() {
        
        uint64_ = 0L;
        onChanged();
        return this;
      }

      private int int32_ ;
      /**
       * <code>int32 int32 = 3;</code>
       */
      public int getInt32() {
        return int32_;
      }
      /**
       * <code>int32 int32 = 3;</code>
       */
      public Builder setInt32(int value) {
        
        int32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 int32 = 3;</code>
       */
      public Builder clearInt32() {
        
        int32_ = 0;
        onChanged();
        return this;
      }

      private long int64_ ;
      /**
       * <code>int64 int64 = 4;</code>
       */
      public long getInt64() {
        return int64_;
      }
      /**
       * <code>int64 int64 = 4;</code>
       */
      public Builder setInt64(long value) {
        
        int64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 int64 = 4;</code>
       */
      public Builder clearInt64() {
        
        int64_ = 0L;
        onChanged();
        return this;
      }

      private int sint32_ ;
      /**
       * <code>sint32 sint32 = 5;</code>
       */
      public int getSint32() {
        return sint32_;
      }
      /**
       * <code>sint32 sint32 = 5;</code>
       */
      public Builder setSint32(int value) {
        
        sint32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 sint32 = 5;</code>
       */
      public Builder clearSint32() {
        
        sint32_ = 0;
        onChanged();
        return this;
      }

      private long sint64_ ;
      /**
       * <code>sint64 sint64 = 6;</code>
       */
      public long getSint64() {
        return sint64_;
      }
      /**
       * <code>sint64 sint64 = 6;</code>
       */
      public Builder setSint64(long value) {
        
        sint64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 sint64 = 6;</code>
       */
      public Builder clearSint64() {
        
        sint64_ = 0L;
        onChanged();
        return this;
      }

      private int fixed32_ ;
      /**
       * <code>fixed32 fixed32 = 7;</code>
       */
      public int getFixed32() {
        return fixed32_;
      }
      /**
       * <code>fixed32 fixed32 = 7;</code>
       */
      public Builder setFixed32(int value) {
        
        fixed32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 fixed32 = 7;</code>
       */
      public Builder clearFixed32() {
        
        fixed32_ = 0;
        onChanged();
        return this;
      }

      private long fixed64_ ;
      /**
       * <code>fixed64 fixed64 = 8;</code>
       */
      public long getFixed64() {
        return fixed64_;
      }
      /**
       * <code>fixed64 fixed64 = 8;</code>
       */
      public Builder setFixed64(long value) {
        
        fixed64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 fixed64 = 8;</code>
       */
      public Builder clearFixed64() {
        
        fixed64_ = 0L;
        onChanged();
        return this;
      }

      private boolean bool_ ;
      /**
       * <code>bool bool = 9;</code>
       */
      public boolean getBool() {
        return bool_;
      }
      /**
       * <code>bool bool = 9;</code>
       */
      public Builder setBool(boolean value) {
        
        bool_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool bool = 9;</code>
       */
      public Builder clearBool() {
        
        bool_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object str_ = "";
      /**
       * <code>string str = 10;</code>
       */
      public java.lang.String getStr() {
        java.lang.Object ref = str_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          str_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string str = 10;</code>
       */
      public com.google.protobuf.ByteString
          getStrBytes() {
        java.lang.Object ref = str_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string str = 10;</code>
       */
      public Builder setStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        str_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string str = 10;</code>
       */
      public Builder clearStr() {
        
        str_ = getDefaultInstance().getStr();
        onChanged();
        return this;
      }
      /**
       * <code>string str = 10;</code>
       */
      public Builder setStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        str_ = value;
        onChanged();
        return this;
      }

      private float float_ ;
      /**
       * <code>float float = 11;</code>
       */
      public float getFloat() {
        return float_;
      }
      /**
       * <code>float float = 11;</code>
       */
      public Builder setFloat(float value) {
        
        float_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float float = 11;</code>
       */
      public Builder clearFloat() {
        
        float_ = 0F;
        onChanged();
        return this;
      }

      private double double_ ;
      /**
       * <code>double double = 12;</code>
       */
      public double getDouble() {
        return double_;
      }
      /**
       * <code>double double = 12;</code>
       */
      public Builder setDouble(double value) {
        
        double_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double double = 12;</code>
       */
      public Builder clearDouble() {
        
        double_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp time_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp time = 13;</code>
       */
      public boolean hasTime() {
        return timeBuilder_ != null || time_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 13;</code>
       */
      public com.google.protobuf.Timestamp getTime() {
        if (timeBuilder_ == null) {
          return time_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : time_;
        } else {
          return timeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp time = 13;</code>
       */
      public Builder setTime(com.google.protobuf.Timestamp value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          time_ = value;
          onChanged();
        } else {
          timeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 13;</code>
       */
      public Builder setTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timeBuilder_ == null) {
          time_ = builderForValue.build();
          onChanged();
        } else {
          timeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 13;</code>
       */
      public Builder mergeTime(com.google.protobuf.Timestamp value) {
        if (timeBuilder_ == null) {
          if (time_ != null) {
            time_ =
              com.google.protobuf.Timestamp.newBuilder(time_).mergeFrom(value).buildPartial();
          } else {
            time_ = value;
          }
          onChanged();
        } else {
          timeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 13;</code>
       */
      public Builder clearTime() {
        if (timeBuilder_ == null) {
          time_ = null;
          onChanged();
        } else {
          time_ = null;
          timeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp time = 13;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimeBuilder() {
        
        onChanged();
        return getTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp time = 13;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimeOrBuilder() {
        if (timeBuilder_ != null) {
          return timeBuilder_.getMessageOrBuilder();
        } else {
          return time_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : time_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp time = 13;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimeFieldBuilder() {
        if (timeBuilder_ == null) {
          timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTime(),
                  getParentForChildren(),
                  isClean());
          time_ = null;
        }
        return timeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Data)
    }

    // @@protoc_insertion_point(class_scope:Data)
    private static final learnProto.selfTest.MyTest.Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new learnProto.selfTest.MyTest.Data();
    }

    public static learnProto.selfTest.MyTest.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    public learnProto.selfTest.MyTest.Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\032\037google/protobuf/timestamp." +
      "proto\032\031google/protobuf/any.proto\032\036google" +
      "/protobuf/wrappers.proto\"\352\001\n\004Data\022\016\n\006uin" +
      "t32\030\001 \001(\r\022\016\n\006uint64\030\002 \001(\004\022\r\n\005int32\030\003 \001(\005" +
      "\022\r\n\005int64\030\004 \001(\003\022\016\n\006sint32\030\005 \001(\021\022\016\n\006sint6" +
      "4\030\006 \001(\022\022\017\n\007fixed32\030\007 \001(\007\022\017\n\007fixed64\030\010 \001(" +
      "\006\022\014\n\004bool\030\t \001(\010\022\013\n\003str\030\n \001(\t\022\r\n\005float\030\013 " +
      "\001(\002\022\016\n\006double\030\014 \001(\001\022(\n\004time\030\r \001(\0132\032.goog" +
      "le.protobuf.TimestampB\035\n\023learnProto.self" +
      "TestB\006MyTestb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Data_descriptor,
        new java.lang.String[] { "Uint32", "Uint64", "Int32", "Int64", "Sint32", "Sint64", "Fixed32", "Fixed64", "Bool", "Str", "Float", "Double", "Time", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
