// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package learnProto.practiceTest.protoModel;

public final class PersonModel {
  private PersonModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prcticeProto_base_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_prcticeProto_base_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prcticeProto_base_Person_Location_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_prcticeProto_base_Person_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022\021prcticeProto.base\"\371\001\n\006Pe" +
      "rson\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\0220\n\006gende" +
      "r\030\003 \001(\0162 .prcticeProto.base.Person.Gende" +
      "r\022\016\n\006height\030\004 \001(\002\022\016\n\006weight\030\005 \001(\001\0224\n\010loc" +
      "ation\030\006 \001(\0132\".prcticeProto.base.Person.L" +
      "ocation\032.\n\010Location\022\021\n\tplaceName\030\001 \001(\t\022\017" +
      "\n\007placeId\030\002 \001(\004\"\034\n\006Gender\022\007\n\003man\020\000\022\t\n\005wo" +
      "man\020\001B3\n\"learnProto.practiceTest.protoMo" +
      "delB\013PersonModelP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_prcticeProto_base_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_prcticeProto_base_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_prcticeProto_base_Person_descriptor,
        new java.lang.String[] { "Name", "Age", "Gender", "Height", "Weight", "Location", });
    internal_static_prcticeProto_base_Person_Location_descriptor =
      internal_static_prcticeProto_base_Person_descriptor.getNestedTypes().get(0);
    internal_static_prcticeProto_base_Person_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_prcticeProto_base_Person_Location_descriptor,
        new java.lang.String[] { "PlaceName", "PlaceId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
