// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package learnProto.practiceTest.protoModel;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:prcticeProto.base.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>.prcticeProto.base.Person.Gender gender = 3;</code>
   */
  int getGenderValue();
  /**
   * <code>.prcticeProto.base.Person.Gender gender = 3;</code>
   */
  learnProto.practiceTest.protoModel.Person.Gender getGender();

  /**
   * <code>float height = 4;</code>
   */
  float getHeight();

  /**
   * <code>double weight = 5;</code>
   */
  double getWeight();

  /**
   * <code>.prcticeProto.base.Person.Location location = 6;</code>
   */
  boolean hasLocation();
  /**
   * <code>.prcticeProto.base.Person.Location location = 6;</code>
   */
  learnProto.practiceTest.protoModel.Person.Location getLocation();
  /**
   * <code>.prcticeProto.base.Person.Location location = 6;</code>
   */
  learnProto.practiceTest.protoModel.Person.LocationOrBuilder getLocationOrBuilder();
}
