// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package learnProto.practiceTest.protoModel;

/**
 * Protobuf type {@code prcticeProto.base.Person}
 */
public  final class Person extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:prcticeProto.base.Person)
    PersonOrBuilder {
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    name_ = "";
    age_ = 0;
    gender_ = 0;
    height_ = 0F;
    weight_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Person(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 16: {

            age_ = input.readInt32();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            gender_ = rawValue;
            break;
          }
          case 37: {

            height_ = input.readFloat();
            break;
          }
          case 41: {

            weight_ = input.readDouble();
            break;
          }
          case 50: {
            learnProto.practiceTest.protoModel.Person.Location.Builder subBuilder = null;
            if (location_ != null) {
              subBuilder = location_.toBuilder();
            }
            location_ = input.readMessage(learnProto.practiceTest.protoModel.Person.Location.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(location_);
              location_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return learnProto.practiceTest.protoModel.PersonModel.internal_static_prcticeProto_base_Person_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return learnProto.practiceTest.protoModel.PersonModel.internal_static_prcticeProto_base_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            learnProto.practiceTest.protoModel.Person.class, learnProto.practiceTest.protoModel.Person.Builder.class);
  }

  /**
   * Protobuf enum {@code prcticeProto.base.Person.Gender}
   */
  public enum Gender
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>man = 0;</code>
     */
    man(0),
    /**
     * <code>woman = 1;</code>
     */
    woman(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>man = 0;</code>
     */
    public static final int man_VALUE = 0;
    /**
     * <code>woman = 1;</code>
     */
    public static final int woman_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Gender valueOf(int value) {
      return forNumber(value);
    }

    public static Gender forNumber(int value) {
      switch (value) {
        case 0: return man;
        case 1: return woman;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Gender> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
            public Gender findValueByNumber(int number) {
              return Gender.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return learnProto.practiceTest.protoModel.Person.getDescriptor().getEnumTypes().get(0);
    }

    private static final Gender[] VALUES = values();

    public static Gender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Gender(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:prcticeProto.base.Person.Gender)
  }

  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:prcticeProto.base.Person.Location)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string placeName = 1;</code>
     */
    java.lang.String getPlaceName();
    /**
     * <code>string placeName = 1;</code>
     */
    com.google.protobuf.ByteString
        getPlaceNameBytes();

    /**
     * <code>uint64 placeId = 2;</code>
     */
    long getPlaceId();
  }
  /**
   * Protobuf type {@code prcticeProto.base.Person.Location}
   */
  public  static final class Location extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:prcticeProto.base.Person.Location)
      LocationOrBuilder {
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Location() {
      placeName_ = "";
      placeId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              placeName_ = s;
              break;
            }
            case 16: {

              placeId_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return learnProto.practiceTest.protoModel.PersonModel.internal_static_prcticeProto_base_Person_Location_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return learnProto.practiceTest.protoModel.PersonModel.internal_static_prcticeProto_base_Person_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              learnProto.practiceTest.protoModel.Person.Location.class, learnProto.practiceTest.protoModel.Person.Location.Builder.class);
    }

    public static final int PLACENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object placeName_;
    /**
     * <code>string placeName = 1;</code>
     */
    public java.lang.String getPlaceName() {
      java.lang.Object ref = placeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        placeName_ = s;
        return s;
      }
    }
    /**
     * <code>string placeName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPlaceNameBytes() {
      java.lang.Object ref = placeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        placeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLACEID_FIELD_NUMBER = 2;
    private long placeId_;
    /**
     * <code>uint64 placeId = 2;</code>
     */
    public long getPlaceId() {
      return placeId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPlaceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, placeName_);
      }
      if (placeId_ != 0L) {
        output.writeUInt64(2, placeId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPlaceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, placeName_);
      }
      if (placeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, placeId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof learnProto.practiceTest.protoModel.Person.Location)) {
        return super.equals(obj);
      }
      learnProto.practiceTest.protoModel.Person.Location other = (learnProto.practiceTest.protoModel.Person.Location) obj;

      boolean result = true;
      result = result && getPlaceName()
          .equals(other.getPlaceName());
      result = result && (getPlaceId()
          == other.getPlaceId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLACENAME_FIELD_NUMBER;
      hash = (53 * hash) + getPlaceName().hashCode();
      hash = (37 * hash) + PLACEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlaceId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static learnProto.practiceTest.protoModel.Person.Location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static learnProto.practiceTest.protoModel.Person.Location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static learnProto.practiceTest.protoModel.Person.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static learnProto.practiceTest.protoModel.Person.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static learnProto.practiceTest.protoModel.Person.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static learnProto.practiceTest.protoModel.Person.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static learnProto.practiceTest.protoModel.Person.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static learnProto.practiceTest.protoModel.Person.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static learnProto.practiceTest.protoModel.Person.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static learnProto.practiceTest.protoModel.Person.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static learnProto.practiceTest.protoModel.Person.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static learnProto.practiceTest.protoModel.Person.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(learnProto.practiceTest.protoModel.Person.Location prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code prcticeProto.base.Person.Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:prcticeProto.base.Person.Location)
        learnProto.practiceTest.protoModel.Person.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return learnProto.practiceTest.protoModel.PersonModel.internal_static_prcticeProto_base_Person_Location_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return learnProto.practiceTest.protoModel.PersonModel.internal_static_prcticeProto_base_Person_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                learnProto.practiceTest.protoModel.Person.Location.class, learnProto.practiceTest.protoModel.Person.Location.Builder.class);
      }

      // Construct using learnProto.practiceTest.protoModel.Person.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        placeName_ = "";

        placeId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return learnProto.practiceTest.protoModel.PersonModel.internal_static_prcticeProto_base_Person_Location_descriptor;
      }

      public learnProto.practiceTest.protoModel.Person.Location getDefaultInstanceForType() {
        return learnProto.practiceTest.protoModel.Person.Location.getDefaultInstance();
      }

      public learnProto.practiceTest.protoModel.Person.Location build() {
        learnProto.practiceTest.protoModel.Person.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public learnProto.practiceTest.protoModel.Person.Location buildPartial() {
        learnProto.practiceTest.protoModel.Person.Location result = new learnProto.practiceTest.protoModel.Person.Location(this);
        result.placeName_ = placeName_;
        result.placeId_ = placeId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof learnProto.practiceTest.protoModel.Person.Location) {
          return mergeFrom((learnProto.practiceTest.protoModel.Person.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(learnProto.practiceTest.protoModel.Person.Location other) {
        if (other == learnProto.practiceTest.protoModel.Person.Location.getDefaultInstance()) return this;
        if (!other.getPlaceName().isEmpty()) {
          placeName_ = other.placeName_;
          onChanged();
        }
        if (other.getPlaceId() != 0L) {
          setPlaceId(other.getPlaceId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        learnProto.practiceTest.protoModel.Person.Location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (learnProto.practiceTest.protoModel.Person.Location) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object placeName_ = "";
      /**
       * <code>string placeName = 1;</code>
       */
      public java.lang.String getPlaceName() {
        java.lang.Object ref = placeName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          placeName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string placeName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPlaceNameBytes() {
        java.lang.Object ref = placeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          placeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string placeName = 1;</code>
       */
      public Builder setPlaceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        placeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string placeName = 1;</code>
       */
      public Builder clearPlaceName() {
        
        placeName_ = getDefaultInstance().getPlaceName();
        onChanged();
        return this;
      }
      /**
       * <code>string placeName = 1;</code>
       */
      public Builder setPlaceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        placeName_ = value;
        onChanged();
        return this;
      }

      private long placeId_ ;
      /**
       * <code>uint64 placeId = 2;</code>
       */
      public long getPlaceId() {
        return placeId_;
      }
      /**
       * <code>uint64 placeId = 2;</code>
       */
      public Builder setPlaceId(long value) {
        
        placeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 placeId = 2;</code>
       */
      public Builder clearPlaceId() {
        
        placeId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:prcticeProto.base.Person.Location)
    }

    // @@protoc_insertion_point(class_scope:prcticeProto.base.Person.Location)
    private static final learnProto.practiceTest.protoModel.Person.Location DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new learnProto.practiceTest.protoModel.Person.Location();
    }

    public static learnProto.practiceTest.protoModel.Person.Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Location>
        PARSER = new com.google.protobuf.AbstractParser<Location>() {
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Location(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Location> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    public learnProto.practiceTest.protoModel.Person.Location getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGE_FIELD_NUMBER = 2;
  private int age_;
  /**
   * <code>int32 age = 2;</code>
   */
  public int getAge() {
    return age_;
  }

  public static final int GENDER_FIELD_NUMBER = 3;
  private int gender_;
  /**
   * <code>.prcticeProto.base.Person.Gender gender = 3;</code>
   */
  public int getGenderValue() {
    return gender_;
  }
  /**
   * <code>.prcticeProto.base.Person.Gender gender = 3;</code>
   */
  public learnProto.practiceTest.protoModel.Person.Gender getGender() {
    learnProto.practiceTest.protoModel.Person.Gender result = learnProto.practiceTest.protoModel.Person.Gender.valueOf(gender_);
    return result == null ? learnProto.practiceTest.protoModel.Person.Gender.UNRECOGNIZED : result;
  }

  public static final int HEIGHT_FIELD_NUMBER = 4;
  private float height_;
  /**
   * <code>float height = 4;</code>
   */
  public float getHeight() {
    return height_;
  }

  public static final int WEIGHT_FIELD_NUMBER = 5;
  private double weight_;
  /**
   * <code>double weight = 5;</code>
   */
  public double getWeight() {
    return weight_;
  }

  public static final int LOCATION_FIELD_NUMBER = 6;
  private learnProto.practiceTest.protoModel.Person.Location location_;
  /**
   * <code>.prcticeProto.base.Person.Location location = 6;</code>
   */
  public boolean hasLocation() {
    return location_ != null;
  }
  /**
   * <code>.prcticeProto.base.Person.Location location = 6;</code>
   */
  public learnProto.practiceTest.protoModel.Person.Location getLocation() {
    return location_ == null ? learnProto.practiceTest.protoModel.Person.Location.getDefaultInstance() : location_;
  }
  /**
   * <code>.prcticeProto.base.Person.Location location = 6;</code>
   */
  public learnProto.practiceTest.protoModel.Person.LocationOrBuilder getLocationOrBuilder() {
    return getLocation();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (age_ != 0) {
      output.writeInt32(2, age_);
    }
    if (gender_ != learnProto.practiceTest.protoModel.Person.Gender.man.getNumber()) {
      output.writeEnum(3, gender_);
    }
    if (height_ != 0F) {
      output.writeFloat(4, height_);
    }
    if (weight_ != 0D) {
      output.writeDouble(5, weight_);
    }
    if (location_ != null) {
      output.writeMessage(6, getLocation());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, age_);
    }
    if (gender_ != learnProto.practiceTest.protoModel.Person.Gender.man.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, gender_);
    }
    if (height_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, height_);
    }
    if (weight_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, weight_);
    }
    if (location_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getLocation());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof learnProto.practiceTest.protoModel.Person)) {
      return super.equals(obj);
    }
    learnProto.practiceTest.protoModel.Person other = (learnProto.practiceTest.protoModel.Person) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && (getAge()
        == other.getAge());
    result = result && gender_ == other.gender_;
    result = result && (
        java.lang.Float.floatToIntBits(getHeight())
        == java.lang.Float.floatToIntBits(
            other.getHeight()));
    result = result && (
        java.lang.Double.doubleToLongBits(getWeight())
        == java.lang.Double.doubleToLongBits(
            other.getWeight()));
    result = result && (hasLocation() == other.hasLocation());
    if (hasLocation()) {
      result = result && getLocation()
          .equals(other.getLocation());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    hash = (37 * hash) + GENDER_FIELD_NUMBER;
    hash = (53 * hash) + gender_;
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getHeight());
    hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWeight()));
    if (hasLocation()) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static learnProto.practiceTest.protoModel.Person parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static learnProto.practiceTest.protoModel.Person parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static learnProto.practiceTest.protoModel.Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static learnProto.practiceTest.protoModel.Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static learnProto.practiceTest.protoModel.Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static learnProto.practiceTest.protoModel.Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static learnProto.practiceTest.protoModel.Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static learnProto.practiceTest.protoModel.Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static learnProto.practiceTest.protoModel.Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static learnProto.practiceTest.protoModel.Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static learnProto.practiceTest.protoModel.Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static learnProto.practiceTest.protoModel.Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(learnProto.practiceTest.protoModel.Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code prcticeProto.base.Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:prcticeProto.base.Person)
      learnProto.practiceTest.protoModel.PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return learnProto.practiceTest.protoModel.PersonModel.internal_static_prcticeProto_base_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return learnProto.practiceTest.protoModel.PersonModel.internal_static_prcticeProto_base_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              learnProto.practiceTest.protoModel.Person.class, learnProto.practiceTest.protoModel.Person.Builder.class);
    }

    // Construct using learnProto.practiceTest.protoModel.Person.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      name_ = "";

      age_ = 0;

      gender_ = 0;

      height_ = 0F;

      weight_ = 0D;

      if (locationBuilder_ == null) {
        location_ = null;
      } else {
        location_ = null;
        locationBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return learnProto.practiceTest.protoModel.PersonModel.internal_static_prcticeProto_base_Person_descriptor;
    }

    public learnProto.practiceTest.protoModel.Person getDefaultInstanceForType() {
      return learnProto.practiceTest.protoModel.Person.getDefaultInstance();
    }

    public learnProto.practiceTest.protoModel.Person build() {
      learnProto.practiceTest.protoModel.Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public learnProto.practiceTest.protoModel.Person buildPartial() {
      learnProto.practiceTest.protoModel.Person result = new learnProto.practiceTest.protoModel.Person(this);
      result.name_ = name_;
      result.age_ = age_;
      result.gender_ = gender_;
      result.height_ = height_;
      result.weight_ = weight_;
      if (locationBuilder_ == null) {
        result.location_ = location_;
      } else {
        result.location_ = locationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof learnProto.practiceTest.protoModel.Person) {
        return mergeFrom((learnProto.practiceTest.protoModel.Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(learnProto.practiceTest.protoModel.Person other) {
      if (other == learnProto.practiceTest.protoModel.Person.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (other.gender_ != 0) {
        setGenderValue(other.getGenderValue());
      }
      if (other.getHeight() != 0F) {
        setHeight(other.getHeight());
      }
      if (other.getWeight() != 0D) {
        setWeight(other.getWeight());
      }
      if (other.hasLocation()) {
        mergeLocation(other.getLocation());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      learnProto.practiceTest.protoModel.Person parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (learnProto.practiceTest.protoModel.Person) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <code>int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }
    /**
     * <code>int32 age = 2;</code>
     */
    public Builder setAge(int value) {
      
      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 age = 2;</code>
     */
    public Builder clearAge() {
      
      age_ = 0;
      onChanged();
      return this;
    }

    private int gender_ = 0;
    /**
     * <code>.prcticeProto.base.Person.Gender gender = 3;</code>
     */
    public int getGenderValue() {
      return gender_;
    }
    /**
     * <code>.prcticeProto.base.Person.Gender gender = 3;</code>
     */
    public Builder setGenderValue(int value) {
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.prcticeProto.base.Person.Gender gender = 3;</code>
     */
    public learnProto.practiceTest.protoModel.Person.Gender getGender() {
      learnProto.practiceTest.protoModel.Person.Gender result = learnProto.practiceTest.protoModel.Person.Gender.valueOf(gender_);
      return result == null ? learnProto.practiceTest.protoModel.Person.Gender.UNRECOGNIZED : result;
    }
    /**
     * <code>.prcticeProto.base.Person.Gender gender = 3;</code>
     */
    public Builder setGender(learnProto.practiceTest.protoModel.Person.Gender value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      gender_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.prcticeProto.base.Person.Gender gender = 3;</code>
     */
    public Builder clearGender() {
      
      gender_ = 0;
      onChanged();
      return this;
    }

    private float height_ ;
    /**
     * <code>float height = 4;</code>
     */
    public float getHeight() {
      return height_;
    }
    /**
     * <code>float height = 4;</code>
     */
    public Builder setHeight(float value) {
      
      height_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float height = 4;</code>
     */
    public Builder clearHeight() {
      
      height_ = 0F;
      onChanged();
      return this;
    }

    private double weight_ ;
    /**
     * <code>double weight = 5;</code>
     */
    public double getWeight() {
      return weight_;
    }
    /**
     * <code>double weight = 5;</code>
     */
    public Builder setWeight(double value) {
      
      weight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double weight = 5;</code>
     */
    public Builder clearWeight() {
      
      weight_ = 0D;
      onChanged();
      return this;
    }

    private learnProto.practiceTest.protoModel.Person.Location location_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        learnProto.practiceTest.protoModel.Person.Location, learnProto.practiceTest.protoModel.Person.Location.Builder, learnProto.practiceTest.protoModel.Person.LocationOrBuilder> locationBuilder_;
    /**
     * <code>.prcticeProto.base.Person.Location location = 6;</code>
     */
    public boolean hasLocation() {
      return locationBuilder_ != null || location_ != null;
    }
    /**
     * <code>.prcticeProto.base.Person.Location location = 6;</code>
     */
    public learnProto.practiceTest.protoModel.Person.Location getLocation() {
      if (locationBuilder_ == null) {
        return location_ == null ? learnProto.practiceTest.protoModel.Person.Location.getDefaultInstance() : location_;
      } else {
        return locationBuilder_.getMessage();
      }
    }
    /**
     * <code>.prcticeProto.base.Person.Location location = 6;</code>
     */
    public Builder setLocation(learnProto.practiceTest.protoModel.Person.Location value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        location_ = value;
        onChanged();
      } else {
        locationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.prcticeProto.base.Person.Location location = 6;</code>
     */
    public Builder setLocation(
        learnProto.practiceTest.protoModel.Person.Location.Builder builderForValue) {
      if (locationBuilder_ == null) {
        location_ = builderForValue.build();
        onChanged();
      } else {
        locationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.prcticeProto.base.Person.Location location = 6;</code>
     */
    public Builder mergeLocation(learnProto.practiceTest.protoModel.Person.Location value) {
      if (locationBuilder_ == null) {
        if (location_ != null) {
          location_ =
            learnProto.practiceTest.protoModel.Person.Location.newBuilder(location_).mergeFrom(value).buildPartial();
        } else {
          location_ = value;
        }
        onChanged();
      } else {
        locationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.prcticeProto.base.Person.Location location = 6;</code>
     */
    public Builder clearLocation() {
      if (locationBuilder_ == null) {
        location_ = null;
        onChanged();
      } else {
        location_ = null;
        locationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.prcticeProto.base.Person.Location location = 6;</code>
     */
    public learnProto.practiceTest.protoModel.Person.Location.Builder getLocationBuilder() {
      
      onChanged();
      return getLocationFieldBuilder().getBuilder();
    }
    /**
     * <code>.prcticeProto.base.Person.Location location = 6;</code>
     */
    public learnProto.practiceTest.protoModel.Person.LocationOrBuilder getLocationOrBuilder() {
      if (locationBuilder_ != null) {
        return locationBuilder_.getMessageOrBuilder();
      } else {
        return location_ == null ?
            learnProto.practiceTest.protoModel.Person.Location.getDefaultInstance() : location_;
      }
    }
    /**
     * <code>.prcticeProto.base.Person.Location location = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        learnProto.practiceTest.protoModel.Person.Location, learnProto.practiceTest.protoModel.Person.Location.Builder, learnProto.practiceTest.protoModel.Person.LocationOrBuilder> 
        getLocationFieldBuilder() {
      if (locationBuilder_ == null) {
        locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            learnProto.practiceTest.protoModel.Person.Location, learnProto.practiceTest.protoModel.Person.Location.Builder, learnProto.practiceTest.protoModel.Person.LocationOrBuilder>(
                getLocation(),
                getParentForChildren(),
                isClean());
        location_ = null;
      }
      return locationBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:prcticeProto.base.Person)
  }

  // @@protoc_insertion_point(class_scope:prcticeProto.base.Person)
  private static final learnProto.practiceTest.protoModel.Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new learnProto.practiceTest.protoModel.Person();
  }

  public static learnProto.practiceTest.protoModel.Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  public learnProto.practiceTest.protoModel.Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

