// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package learnProto.practiceTest.protoModel;

public final class SchoolModel {
  private SchoolModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prcticeProto_messages_School_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_prcticeProto_messages_School_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prcticeProto_messages_School_Location_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_prcticeProto_messages_School_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto\022\025prcticeProto.messages\032\031goo" +
      "gle/protobuf/any.proto\032&practiceProto/ca" +
      "tegories/student.proto\"\333\001\n\006School\022>\n\016sch" +
      "oolLocation\030\001 \001(\0132&.prcticeProto.message" +
      "s.School.Location\022\016\n\006isOpen\030\002 \001(\010\0225\n\013all" +
      "Students\030\003 \003(\0132 .prcticeProto.categories" +
      ".Student\022$\n\006extend\030\004 \001(\0132\024.google.protob" +
      "uf.Any\032$\n\010Location\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002" +
      " \001(\rB3\n\"learnProto.practiceTest.protoMod" +
      "elB\013SchoolModelP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          learnProto.practiceTest.protoModel.StudentModel.getDescriptor(),
        }, assigner);
    internal_static_prcticeProto_messages_School_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_prcticeProto_messages_School_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_prcticeProto_messages_School_descriptor,
        new java.lang.String[] { "SchoolLocation", "IsOpen", "AllStudents", "Extend", });
    internal_static_prcticeProto_messages_School_Location_descriptor =
      internal_static_prcticeProto_messages_School_descriptor.getNestedTypes().get(0);
    internal_static_prcticeProto_messages_School_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_prcticeProto_messages_School_Location_descriptor,
        new java.lang.String[] { "Name", "Id", });
    com.google.protobuf.AnyProto.getDescriptor();
    learnProto.practiceTest.protoModel.StudentModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
