// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package learnProto.practiceTest.protoModel;

/**
 * Protobuf type {@code prcticeProto.messages.School}
 */
public  final class School extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:prcticeProto.messages.School)
    SchoolOrBuilder {
  // Use School.newBuilder() to construct.
  private School(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private School() {
    isOpen_ = false;
    allStudents_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private School(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            learnProto.practiceTest.protoModel.School.Location.Builder subBuilder = null;
            if (schoolLocation_ != null) {
              subBuilder = schoolLocation_.toBuilder();
            }
            schoolLocation_ = input.readMessage(learnProto.practiceTest.protoModel.School.Location.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(schoolLocation_);
              schoolLocation_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            isOpen_ = input.readBool();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              allStudents_ = new java.util.ArrayList<learnProto.practiceTest.protoModel.Student>();
              mutable_bitField0_ |= 0x00000004;
            }
            allStudents_.add(
                input.readMessage(learnProto.practiceTest.protoModel.Student.parser(), extensionRegistry));
            break;
          }
          case 34: {
            com.google.protobuf.Any.Builder subBuilder = null;
            if (extend_ != null) {
              subBuilder = extend_.toBuilder();
            }
            extend_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(extend_);
              extend_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        allStudents_ = java.util.Collections.unmodifiableList(allStudents_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return learnProto.practiceTest.protoModel.SchoolModel.internal_static_prcticeProto_messages_School_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return learnProto.practiceTest.protoModel.SchoolModel.internal_static_prcticeProto_messages_School_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            learnProto.practiceTest.protoModel.School.class, learnProto.practiceTest.protoModel.School.Builder.class);
  }

  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:prcticeProto.messages.School.Location)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>uint32 id = 2;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code prcticeProto.messages.School.Location}
   */
  public  static final class Location extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:prcticeProto.messages.School.Location)
      LocationOrBuilder {
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Location() {
      name_ = "";
      id_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              id_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return learnProto.practiceTest.protoModel.SchoolModel.internal_static_prcticeProto_messages_School_Location_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return learnProto.practiceTest.protoModel.SchoolModel.internal_static_prcticeProto_messages_School_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              learnProto.practiceTest.protoModel.School.Location.class, learnProto.practiceTest.protoModel.School.Location.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>uint32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (id_ != 0) {
        output.writeUInt32(2, id_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, id_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof learnProto.practiceTest.protoModel.School.Location)) {
        return super.equals(obj);
      }
      learnProto.practiceTest.protoModel.School.Location other = (learnProto.practiceTest.protoModel.School.Location) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getId()
          == other.getId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static learnProto.practiceTest.protoModel.School.Location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static learnProto.practiceTest.protoModel.School.Location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static learnProto.practiceTest.protoModel.School.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static learnProto.practiceTest.protoModel.School.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static learnProto.practiceTest.protoModel.School.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static learnProto.practiceTest.protoModel.School.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static learnProto.practiceTest.protoModel.School.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static learnProto.practiceTest.protoModel.School.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static learnProto.practiceTest.protoModel.School.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static learnProto.practiceTest.protoModel.School.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static learnProto.practiceTest.protoModel.School.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static learnProto.practiceTest.protoModel.School.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(learnProto.practiceTest.protoModel.School.Location prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code prcticeProto.messages.School.Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:prcticeProto.messages.School.Location)
        learnProto.practiceTest.protoModel.School.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return learnProto.practiceTest.protoModel.SchoolModel.internal_static_prcticeProto_messages_School_Location_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return learnProto.practiceTest.protoModel.SchoolModel.internal_static_prcticeProto_messages_School_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                learnProto.practiceTest.protoModel.School.Location.class, learnProto.practiceTest.protoModel.School.Location.Builder.class);
      }

      // Construct using learnProto.practiceTest.protoModel.School.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        id_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return learnProto.practiceTest.protoModel.SchoolModel.internal_static_prcticeProto_messages_School_Location_descriptor;
      }

      public learnProto.practiceTest.protoModel.School.Location getDefaultInstanceForType() {
        return learnProto.practiceTest.protoModel.School.Location.getDefaultInstance();
      }

      public learnProto.practiceTest.protoModel.School.Location build() {
        learnProto.practiceTest.protoModel.School.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public learnProto.practiceTest.protoModel.School.Location buildPartial() {
        learnProto.practiceTest.protoModel.School.Location result = new learnProto.practiceTest.protoModel.School.Location(this);
        result.name_ = name_;
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof learnProto.practiceTest.protoModel.School.Location) {
          return mergeFrom((learnProto.practiceTest.protoModel.School.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(learnProto.practiceTest.protoModel.School.Location other) {
        if (other == learnProto.practiceTest.protoModel.School.Location.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        learnProto.practiceTest.protoModel.School.Location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (learnProto.practiceTest.protoModel.School.Location) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>uint32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>uint32 id = 2;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:prcticeProto.messages.School.Location)
    }

    // @@protoc_insertion_point(class_scope:prcticeProto.messages.School.Location)
    private static final learnProto.practiceTest.protoModel.School.Location DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new learnProto.practiceTest.protoModel.School.Location();
    }

    public static learnProto.practiceTest.protoModel.School.Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Location>
        PARSER = new com.google.protobuf.AbstractParser<Location>() {
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Location(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Location> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    public learnProto.practiceTest.protoModel.School.Location getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int SCHOOLLOCATION_FIELD_NUMBER = 1;
  private learnProto.practiceTest.protoModel.School.Location schoolLocation_;
  /**
   * <code>.prcticeProto.messages.School.Location schoolLocation = 1;</code>
   */
  public boolean hasSchoolLocation() {
    return schoolLocation_ != null;
  }
  /**
   * <code>.prcticeProto.messages.School.Location schoolLocation = 1;</code>
   */
  public learnProto.practiceTest.protoModel.School.Location getSchoolLocation() {
    return schoolLocation_ == null ? learnProto.practiceTest.protoModel.School.Location.getDefaultInstance() : schoolLocation_;
  }
  /**
   * <code>.prcticeProto.messages.School.Location schoolLocation = 1;</code>
   */
  public learnProto.practiceTest.protoModel.School.LocationOrBuilder getSchoolLocationOrBuilder() {
    return getSchoolLocation();
  }

  public static final int ISOPEN_FIELD_NUMBER = 2;
  private boolean isOpen_;
  /**
   * <code>bool isOpen = 2;</code>
   */
  public boolean getIsOpen() {
    return isOpen_;
  }

  public static final int ALLSTUDENTS_FIELD_NUMBER = 3;
  private java.util.List<learnProto.practiceTest.protoModel.Student> allStudents_;
  /**
   * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
   */
  public java.util.List<learnProto.practiceTest.protoModel.Student> getAllStudentsList() {
    return allStudents_;
  }
  /**
   * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
   */
  public java.util.List<? extends learnProto.practiceTest.protoModel.StudentOrBuilder> 
      getAllStudentsOrBuilderList() {
    return allStudents_;
  }
  /**
   * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
   */
  public int getAllStudentsCount() {
    return allStudents_.size();
  }
  /**
   * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
   */
  public learnProto.practiceTest.protoModel.Student getAllStudents(int index) {
    return allStudents_.get(index);
  }
  /**
   * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
   */
  public learnProto.practiceTest.protoModel.StudentOrBuilder getAllStudentsOrBuilder(
      int index) {
    return allStudents_.get(index);
  }

  public static final int EXTEND_FIELD_NUMBER = 4;
  private com.google.protobuf.Any extend_;
  /**
   * <code>.google.protobuf.Any extend = 4;</code>
   */
  public boolean hasExtend() {
    return extend_ != null;
  }
  /**
   * <code>.google.protobuf.Any extend = 4;</code>
   */
  public com.google.protobuf.Any getExtend() {
    return extend_ == null ? com.google.protobuf.Any.getDefaultInstance() : extend_;
  }
  /**
   * <code>.google.protobuf.Any extend = 4;</code>
   */
  public com.google.protobuf.AnyOrBuilder getExtendOrBuilder() {
    return getExtend();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (schoolLocation_ != null) {
      output.writeMessage(1, getSchoolLocation());
    }
    if (isOpen_ != false) {
      output.writeBool(2, isOpen_);
    }
    for (int i = 0; i < allStudents_.size(); i++) {
      output.writeMessage(3, allStudents_.get(i));
    }
    if (extend_ != null) {
      output.writeMessage(4, getExtend());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (schoolLocation_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSchoolLocation());
    }
    if (isOpen_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isOpen_);
    }
    for (int i = 0; i < allStudents_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, allStudents_.get(i));
    }
    if (extend_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getExtend());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof learnProto.practiceTest.protoModel.School)) {
      return super.equals(obj);
    }
    learnProto.practiceTest.protoModel.School other = (learnProto.practiceTest.protoModel.School) obj;

    boolean result = true;
    result = result && (hasSchoolLocation() == other.hasSchoolLocation());
    if (hasSchoolLocation()) {
      result = result && getSchoolLocation()
          .equals(other.getSchoolLocation());
    }
    result = result && (getIsOpen()
        == other.getIsOpen());
    result = result && getAllStudentsList()
        .equals(other.getAllStudentsList());
    result = result && (hasExtend() == other.hasExtend());
    if (hasExtend()) {
      result = result && getExtend()
          .equals(other.getExtend());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSchoolLocation()) {
      hash = (37 * hash) + SCHOOLLOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getSchoolLocation().hashCode();
    }
    hash = (37 * hash) + ISOPEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsOpen());
    if (getAllStudentsCount() > 0) {
      hash = (37 * hash) + ALLSTUDENTS_FIELD_NUMBER;
      hash = (53 * hash) + getAllStudentsList().hashCode();
    }
    if (hasExtend()) {
      hash = (37 * hash) + EXTEND_FIELD_NUMBER;
      hash = (53 * hash) + getExtend().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static learnProto.practiceTest.protoModel.School parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static learnProto.practiceTest.protoModel.School parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static learnProto.practiceTest.protoModel.School parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static learnProto.practiceTest.protoModel.School parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static learnProto.practiceTest.protoModel.School parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static learnProto.practiceTest.protoModel.School parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static learnProto.practiceTest.protoModel.School parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static learnProto.practiceTest.protoModel.School parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static learnProto.practiceTest.protoModel.School parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static learnProto.practiceTest.protoModel.School parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static learnProto.practiceTest.protoModel.School parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static learnProto.practiceTest.protoModel.School parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(learnProto.practiceTest.protoModel.School prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code prcticeProto.messages.School}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:prcticeProto.messages.School)
      learnProto.practiceTest.protoModel.SchoolOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return learnProto.practiceTest.protoModel.SchoolModel.internal_static_prcticeProto_messages_School_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return learnProto.practiceTest.protoModel.SchoolModel.internal_static_prcticeProto_messages_School_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              learnProto.practiceTest.protoModel.School.class, learnProto.practiceTest.protoModel.School.Builder.class);
    }

    // Construct using learnProto.practiceTest.protoModel.School.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAllStudentsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (schoolLocationBuilder_ == null) {
        schoolLocation_ = null;
      } else {
        schoolLocation_ = null;
        schoolLocationBuilder_ = null;
      }
      isOpen_ = false;

      if (allStudentsBuilder_ == null) {
        allStudents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        allStudentsBuilder_.clear();
      }
      if (extendBuilder_ == null) {
        extend_ = null;
      } else {
        extend_ = null;
        extendBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return learnProto.practiceTest.protoModel.SchoolModel.internal_static_prcticeProto_messages_School_descriptor;
    }

    public learnProto.practiceTest.protoModel.School getDefaultInstanceForType() {
      return learnProto.practiceTest.protoModel.School.getDefaultInstance();
    }

    public learnProto.practiceTest.protoModel.School build() {
      learnProto.practiceTest.protoModel.School result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public learnProto.practiceTest.protoModel.School buildPartial() {
      learnProto.practiceTest.protoModel.School result = new learnProto.practiceTest.protoModel.School(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (schoolLocationBuilder_ == null) {
        result.schoolLocation_ = schoolLocation_;
      } else {
        result.schoolLocation_ = schoolLocationBuilder_.build();
      }
      result.isOpen_ = isOpen_;
      if (allStudentsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          allStudents_ = java.util.Collections.unmodifiableList(allStudents_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.allStudents_ = allStudents_;
      } else {
        result.allStudents_ = allStudentsBuilder_.build();
      }
      if (extendBuilder_ == null) {
        result.extend_ = extend_;
      } else {
        result.extend_ = extendBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof learnProto.practiceTest.protoModel.School) {
        return mergeFrom((learnProto.practiceTest.protoModel.School)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(learnProto.practiceTest.protoModel.School other) {
      if (other == learnProto.practiceTest.protoModel.School.getDefaultInstance()) return this;
      if (other.hasSchoolLocation()) {
        mergeSchoolLocation(other.getSchoolLocation());
      }
      if (other.getIsOpen() != false) {
        setIsOpen(other.getIsOpen());
      }
      if (allStudentsBuilder_ == null) {
        if (!other.allStudents_.isEmpty()) {
          if (allStudents_.isEmpty()) {
            allStudents_ = other.allStudents_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAllStudentsIsMutable();
            allStudents_.addAll(other.allStudents_);
          }
          onChanged();
        }
      } else {
        if (!other.allStudents_.isEmpty()) {
          if (allStudentsBuilder_.isEmpty()) {
            allStudentsBuilder_.dispose();
            allStudentsBuilder_ = null;
            allStudents_ = other.allStudents_;
            bitField0_ = (bitField0_ & ~0x00000004);
            allStudentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAllStudentsFieldBuilder() : null;
          } else {
            allStudentsBuilder_.addAllMessages(other.allStudents_);
          }
        }
      }
      if (other.hasExtend()) {
        mergeExtend(other.getExtend());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      learnProto.practiceTest.protoModel.School parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (learnProto.practiceTest.protoModel.School) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private learnProto.practiceTest.protoModel.School.Location schoolLocation_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        learnProto.practiceTest.protoModel.School.Location, learnProto.practiceTest.protoModel.School.Location.Builder, learnProto.practiceTest.protoModel.School.LocationOrBuilder> schoolLocationBuilder_;
    /**
     * <code>.prcticeProto.messages.School.Location schoolLocation = 1;</code>
     */
    public boolean hasSchoolLocation() {
      return schoolLocationBuilder_ != null || schoolLocation_ != null;
    }
    /**
     * <code>.prcticeProto.messages.School.Location schoolLocation = 1;</code>
     */
    public learnProto.practiceTest.protoModel.School.Location getSchoolLocation() {
      if (schoolLocationBuilder_ == null) {
        return schoolLocation_ == null ? learnProto.practiceTest.protoModel.School.Location.getDefaultInstance() : schoolLocation_;
      } else {
        return schoolLocationBuilder_.getMessage();
      }
    }
    /**
     * <code>.prcticeProto.messages.School.Location schoolLocation = 1;</code>
     */
    public Builder setSchoolLocation(learnProto.practiceTest.protoModel.School.Location value) {
      if (schoolLocationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        schoolLocation_ = value;
        onChanged();
      } else {
        schoolLocationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.prcticeProto.messages.School.Location schoolLocation = 1;</code>
     */
    public Builder setSchoolLocation(
        learnProto.practiceTest.protoModel.School.Location.Builder builderForValue) {
      if (schoolLocationBuilder_ == null) {
        schoolLocation_ = builderForValue.build();
        onChanged();
      } else {
        schoolLocationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.prcticeProto.messages.School.Location schoolLocation = 1;</code>
     */
    public Builder mergeSchoolLocation(learnProto.practiceTest.protoModel.School.Location value) {
      if (schoolLocationBuilder_ == null) {
        if (schoolLocation_ != null) {
          schoolLocation_ =
            learnProto.practiceTest.protoModel.School.Location.newBuilder(schoolLocation_).mergeFrom(value).buildPartial();
        } else {
          schoolLocation_ = value;
        }
        onChanged();
      } else {
        schoolLocationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.prcticeProto.messages.School.Location schoolLocation = 1;</code>
     */
    public Builder clearSchoolLocation() {
      if (schoolLocationBuilder_ == null) {
        schoolLocation_ = null;
        onChanged();
      } else {
        schoolLocation_ = null;
        schoolLocationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.prcticeProto.messages.School.Location schoolLocation = 1;</code>
     */
    public learnProto.practiceTest.protoModel.School.Location.Builder getSchoolLocationBuilder() {
      
      onChanged();
      return getSchoolLocationFieldBuilder().getBuilder();
    }
    /**
     * <code>.prcticeProto.messages.School.Location schoolLocation = 1;</code>
     */
    public learnProto.practiceTest.protoModel.School.LocationOrBuilder getSchoolLocationOrBuilder() {
      if (schoolLocationBuilder_ != null) {
        return schoolLocationBuilder_.getMessageOrBuilder();
      } else {
        return schoolLocation_ == null ?
            learnProto.practiceTest.protoModel.School.Location.getDefaultInstance() : schoolLocation_;
      }
    }
    /**
     * <code>.prcticeProto.messages.School.Location schoolLocation = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        learnProto.practiceTest.protoModel.School.Location, learnProto.practiceTest.protoModel.School.Location.Builder, learnProto.practiceTest.protoModel.School.LocationOrBuilder> 
        getSchoolLocationFieldBuilder() {
      if (schoolLocationBuilder_ == null) {
        schoolLocationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            learnProto.practiceTest.protoModel.School.Location, learnProto.practiceTest.protoModel.School.Location.Builder, learnProto.practiceTest.protoModel.School.LocationOrBuilder>(
                getSchoolLocation(),
                getParentForChildren(),
                isClean());
        schoolLocation_ = null;
      }
      return schoolLocationBuilder_;
    }

    private boolean isOpen_ ;
    /**
     * <code>bool isOpen = 2;</code>
     */
    public boolean getIsOpen() {
      return isOpen_;
    }
    /**
     * <code>bool isOpen = 2;</code>
     */
    public Builder setIsOpen(boolean value) {
      
      isOpen_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isOpen = 2;</code>
     */
    public Builder clearIsOpen() {
      
      isOpen_ = false;
      onChanged();
      return this;
    }

    private java.util.List<learnProto.practiceTest.protoModel.Student> allStudents_ =
      java.util.Collections.emptyList();
    private void ensureAllStudentsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        allStudents_ = new java.util.ArrayList<learnProto.practiceTest.protoModel.Student>(allStudents_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        learnProto.practiceTest.protoModel.Student, learnProto.practiceTest.protoModel.Student.Builder, learnProto.practiceTest.protoModel.StudentOrBuilder> allStudentsBuilder_;

    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public java.util.List<learnProto.practiceTest.protoModel.Student> getAllStudentsList() {
      if (allStudentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(allStudents_);
      } else {
        return allStudentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public int getAllStudentsCount() {
      if (allStudentsBuilder_ == null) {
        return allStudents_.size();
      } else {
        return allStudentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public learnProto.practiceTest.protoModel.Student getAllStudents(int index) {
      if (allStudentsBuilder_ == null) {
        return allStudents_.get(index);
      } else {
        return allStudentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public Builder setAllStudents(
        int index, learnProto.practiceTest.protoModel.Student value) {
      if (allStudentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAllStudentsIsMutable();
        allStudents_.set(index, value);
        onChanged();
      } else {
        allStudentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public Builder setAllStudents(
        int index, learnProto.practiceTest.protoModel.Student.Builder builderForValue) {
      if (allStudentsBuilder_ == null) {
        ensureAllStudentsIsMutable();
        allStudents_.set(index, builderForValue.build());
        onChanged();
      } else {
        allStudentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public Builder addAllStudents(learnProto.practiceTest.protoModel.Student value) {
      if (allStudentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAllStudentsIsMutable();
        allStudents_.add(value);
        onChanged();
      } else {
        allStudentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public Builder addAllStudents(
        int index, learnProto.practiceTest.protoModel.Student value) {
      if (allStudentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAllStudentsIsMutable();
        allStudents_.add(index, value);
        onChanged();
      } else {
        allStudentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public Builder addAllStudents(
        learnProto.practiceTest.protoModel.Student.Builder builderForValue) {
      if (allStudentsBuilder_ == null) {
        ensureAllStudentsIsMutable();
        allStudents_.add(builderForValue.build());
        onChanged();
      } else {
        allStudentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public Builder addAllStudents(
        int index, learnProto.practiceTest.protoModel.Student.Builder builderForValue) {
      if (allStudentsBuilder_ == null) {
        ensureAllStudentsIsMutable();
        allStudents_.add(index, builderForValue.build());
        onChanged();
      } else {
        allStudentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public Builder addAllAllStudents(
        java.lang.Iterable<? extends learnProto.practiceTest.protoModel.Student> values) {
      if (allStudentsBuilder_ == null) {
        ensureAllStudentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, allStudents_);
        onChanged();
      } else {
        allStudentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public Builder clearAllStudents() {
      if (allStudentsBuilder_ == null) {
        allStudents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        allStudentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public Builder removeAllStudents(int index) {
      if (allStudentsBuilder_ == null) {
        ensureAllStudentsIsMutable();
        allStudents_.remove(index);
        onChanged();
      } else {
        allStudentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public learnProto.practiceTest.protoModel.Student.Builder getAllStudentsBuilder(
        int index) {
      return getAllStudentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public learnProto.practiceTest.protoModel.StudentOrBuilder getAllStudentsOrBuilder(
        int index) {
      if (allStudentsBuilder_ == null) {
        return allStudents_.get(index);  } else {
        return allStudentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public java.util.List<? extends learnProto.practiceTest.protoModel.StudentOrBuilder> 
         getAllStudentsOrBuilderList() {
      if (allStudentsBuilder_ != null) {
        return allStudentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(allStudents_);
      }
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public learnProto.practiceTest.protoModel.Student.Builder addAllStudentsBuilder() {
      return getAllStudentsFieldBuilder().addBuilder(
          learnProto.practiceTest.protoModel.Student.getDefaultInstance());
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public learnProto.practiceTest.protoModel.Student.Builder addAllStudentsBuilder(
        int index) {
      return getAllStudentsFieldBuilder().addBuilder(
          index, learnProto.practiceTest.protoModel.Student.getDefaultInstance());
    }
    /**
     * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
     */
    public java.util.List<learnProto.practiceTest.protoModel.Student.Builder> 
         getAllStudentsBuilderList() {
      return getAllStudentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        learnProto.practiceTest.protoModel.Student, learnProto.practiceTest.protoModel.Student.Builder, learnProto.practiceTest.protoModel.StudentOrBuilder> 
        getAllStudentsFieldBuilder() {
      if (allStudentsBuilder_ == null) {
        allStudentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            learnProto.practiceTest.protoModel.Student, learnProto.practiceTest.protoModel.Student.Builder, learnProto.practiceTest.protoModel.StudentOrBuilder>(
                allStudents_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        allStudents_ = null;
      }
      return allStudentsBuilder_;
    }

    private com.google.protobuf.Any extend_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> extendBuilder_;
    /**
     * <code>.google.protobuf.Any extend = 4;</code>
     */
    public boolean hasExtend() {
      return extendBuilder_ != null || extend_ != null;
    }
    /**
     * <code>.google.protobuf.Any extend = 4;</code>
     */
    public com.google.protobuf.Any getExtend() {
      if (extendBuilder_ == null) {
        return extend_ == null ? com.google.protobuf.Any.getDefaultInstance() : extend_;
      } else {
        return extendBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Any extend = 4;</code>
     */
    public Builder setExtend(com.google.protobuf.Any value) {
      if (extendBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        extend_ = value;
        onChanged();
      } else {
        extendBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any extend = 4;</code>
     */
    public Builder setExtend(
        com.google.protobuf.Any.Builder builderForValue) {
      if (extendBuilder_ == null) {
        extend_ = builderForValue.build();
        onChanged();
      } else {
        extendBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any extend = 4;</code>
     */
    public Builder mergeExtend(com.google.protobuf.Any value) {
      if (extendBuilder_ == null) {
        if (extend_ != null) {
          extend_ =
            com.google.protobuf.Any.newBuilder(extend_).mergeFrom(value).buildPartial();
        } else {
          extend_ = value;
        }
        onChanged();
      } else {
        extendBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any extend = 4;</code>
     */
    public Builder clearExtend() {
      if (extendBuilder_ == null) {
        extend_ = null;
        onChanged();
      } else {
        extend_ = null;
        extendBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any extend = 4;</code>
     */
    public com.google.protobuf.Any.Builder getExtendBuilder() {
      
      onChanged();
      return getExtendFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Any extend = 4;</code>
     */
    public com.google.protobuf.AnyOrBuilder getExtendOrBuilder() {
      if (extendBuilder_ != null) {
        return extendBuilder_.getMessageOrBuilder();
      } else {
        return extend_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : extend_;
      }
    }
    /**
     * <code>.google.protobuf.Any extend = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getExtendFieldBuilder() {
      if (extendBuilder_ == null) {
        extendBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getExtend(),
                getParentForChildren(),
                isClean());
        extend_ = null;
      }
      return extendBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:prcticeProto.messages.School)
  }

  // @@protoc_insertion_point(class_scope:prcticeProto.messages.School)
  private static final learnProto.practiceTest.protoModel.School DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new learnProto.practiceTest.protoModel.School();
  }

  public static learnProto.practiceTest.protoModel.School getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<School>
      PARSER = new com.google.protobuf.AbstractParser<School>() {
    public School parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new School(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<School> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<School> getParserForType() {
    return PARSER;
  }

  public learnProto.practiceTest.protoModel.School getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

