// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package learnProto.practiceTest.protoModel;

public interface SchoolOrBuilder extends
    // @@protoc_insertion_point(interface_extends:prcticeProto.messages.School)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.prcticeProto.messages.School.Location schoolLocation = 1;</code>
   */
  boolean hasSchoolLocation();
  /**
   * <code>.prcticeProto.messages.School.Location schoolLocation = 1;</code>
   */
  learnProto.practiceTest.protoModel.School.Location getSchoolLocation();
  /**
   * <code>.prcticeProto.messages.School.Location schoolLocation = 1;</code>
   */
  learnProto.practiceTest.protoModel.School.LocationOrBuilder getSchoolLocationOrBuilder();

  /**
   * <code>bool isOpen = 2;</code>
   */
  boolean getIsOpen();

  /**
   * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
   */
  java.util.List<learnProto.practiceTest.protoModel.Student> 
      getAllStudentsList();
  /**
   * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
   */
  learnProto.practiceTest.protoModel.Student getAllStudents(int index);
  /**
   * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
   */
  int getAllStudentsCount();
  /**
   * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
   */
  java.util.List<? extends learnProto.practiceTest.protoModel.StudentOrBuilder> 
      getAllStudentsOrBuilderList();
  /**
   * <code>repeated .prcticeProto.categories.Student allStudents = 3;</code>
   */
  learnProto.practiceTest.protoModel.StudentOrBuilder getAllStudentsOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Any extend = 4;</code>
   */
  boolean hasExtend();
  /**
   * <code>.google.protobuf.Any extend = 4;</code>
   */
  com.google.protobuf.Any getExtend();
  /**
   * <code>.google.protobuf.Any extend = 4;</code>
   */
  com.google.protobuf.AnyOrBuilder getExtendOrBuilder();
}
