// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package learnProto.practiceTest.protoModel;

public final class StudentModel {
  private StudentModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prcticeProto_categories_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_prcticeProto_categories_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstudent.proto\022\027prcticeProto.categories" +
      "\032\037practiceProto/base/person.proto\"V\n\007Stu" +
      "dent\022+\n\010baseInfo\030\001 \001(\0132\031.prcticeProto.ba" +
      "se.Person\022\017\n\007calssId\030\002 \001(\007\022\r\n\005score\030\003 \001(" +
      "\021B4\n\"learnProto.practiceTest.protoModelB" +
      "\014StudentModelP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          learnProto.practiceTest.protoModel.PersonModel.getDescriptor(),
        }, assigner);
    internal_static_prcticeProto_categories_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_prcticeProto_categories_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_prcticeProto_categories_Student_descriptor,
        new java.lang.String[] { "BaseInfo", "CalssId", "Score", });
    learnProto.practiceTest.protoModel.PersonModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
