// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package learnProto.practiceTest.protoModel;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:prcticeProto.categories.Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.prcticeProto.base.Person baseInfo = 1;</code>
   */
  boolean hasBaseInfo();
  /**
   * <code>.prcticeProto.base.Person baseInfo = 1;</code>
   */
  learnProto.practiceTest.protoModel.Person getBaseInfo();
  /**
   * <code>.prcticeProto.base.Person baseInfo = 1;</code>
   */
  learnProto.practiceTest.protoModel.PersonOrBuilder getBaseInfoOrBuilder();

  /**
   * <code>fixed32 calssId = 2;</code>
   */
  int getCalssId();

  /**
   * <code>sint32 score = 3;</code>
   */
  int getScore();
}
