// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package learnProto.practiceTest.protoModel;

/**
 * Protobuf type {@code prcticeProto.categories.Student}
 */
public  final class Student extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:prcticeProto.categories.Student)
    StudentOrBuilder {
  // Use Student.newBuilder() to construct.
  private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Student() {
    calssId_ = 0;
    score_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Student(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            learnProto.practiceTest.protoModel.Person.Builder subBuilder = null;
            if (baseInfo_ != null) {
              subBuilder = baseInfo_.toBuilder();
            }
            baseInfo_ = input.readMessage(learnProto.practiceTest.protoModel.Person.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(baseInfo_);
              baseInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 21: {

            calssId_ = input.readFixed32();
            break;
          }
          case 24: {

            score_ = input.readSInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return learnProto.practiceTest.protoModel.StudentModel.internal_static_prcticeProto_categories_Student_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return learnProto.practiceTest.protoModel.StudentModel.internal_static_prcticeProto_categories_Student_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            learnProto.practiceTest.protoModel.Student.class, learnProto.practiceTest.protoModel.Student.Builder.class);
  }

  public static final int BASEINFO_FIELD_NUMBER = 1;
  private learnProto.practiceTest.protoModel.Person baseInfo_;
  /**
   * <code>.prcticeProto.base.Person baseInfo = 1;</code>
   */
  public boolean hasBaseInfo() {
    return baseInfo_ != null;
  }
  /**
   * <code>.prcticeProto.base.Person baseInfo = 1;</code>
   */
  public learnProto.practiceTest.protoModel.Person getBaseInfo() {
    return baseInfo_ == null ? learnProto.practiceTest.protoModel.Person.getDefaultInstance() : baseInfo_;
  }
  /**
   * <code>.prcticeProto.base.Person baseInfo = 1;</code>
   */
  public learnProto.practiceTest.protoModel.PersonOrBuilder getBaseInfoOrBuilder() {
    return getBaseInfo();
  }

  public static final int CALSSID_FIELD_NUMBER = 2;
  private int calssId_;
  /**
   * <code>fixed32 calssId = 2;</code>
   */
  public int getCalssId() {
    return calssId_;
  }

  public static final int SCORE_FIELD_NUMBER = 3;
  private int score_;
  /**
   * <code>sint32 score = 3;</code>
   */
  public int getScore() {
    return score_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (baseInfo_ != null) {
      output.writeMessage(1, getBaseInfo());
    }
    if (calssId_ != 0) {
      output.writeFixed32(2, calssId_);
    }
    if (score_ != 0) {
      output.writeSInt32(3, score_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (baseInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseInfo());
    }
    if (calssId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(2, calssId_);
    }
    if (score_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(3, score_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof learnProto.practiceTest.protoModel.Student)) {
      return super.equals(obj);
    }
    learnProto.practiceTest.protoModel.Student other = (learnProto.practiceTest.protoModel.Student) obj;

    boolean result = true;
    result = result && (hasBaseInfo() == other.hasBaseInfo());
    if (hasBaseInfo()) {
      result = result && getBaseInfo()
          .equals(other.getBaseInfo());
    }
    result = result && (getCalssId()
        == other.getCalssId());
    result = result && (getScore()
        == other.getScore());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseInfo()) {
      hash = (37 * hash) + BASEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getBaseInfo().hashCode();
    }
    hash = (37 * hash) + CALSSID_FIELD_NUMBER;
    hash = (53 * hash) + getCalssId();
    hash = (37 * hash) + SCORE_FIELD_NUMBER;
    hash = (53 * hash) + getScore();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static learnProto.practiceTest.protoModel.Student parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static learnProto.practiceTest.protoModel.Student parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static learnProto.practiceTest.protoModel.Student parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static learnProto.practiceTest.protoModel.Student parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static learnProto.practiceTest.protoModel.Student parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static learnProto.practiceTest.protoModel.Student parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static learnProto.practiceTest.protoModel.Student parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static learnProto.practiceTest.protoModel.Student parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static learnProto.practiceTest.protoModel.Student parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static learnProto.practiceTest.protoModel.Student parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static learnProto.practiceTest.protoModel.Student parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static learnProto.practiceTest.protoModel.Student parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(learnProto.practiceTest.protoModel.Student prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code prcticeProto.categories.Student}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:prcticeProto.categories.Student)
      learnProto.practiceTest.protoModel.StudentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return learnProto.practiceTest.protoModel.StudentModel.internal_static_prcticeProto_categories_Student_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return learnProto.practiceTest.protoModel.StudentModel.internal_static_prcticeProto_categories_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              learnProto.practiceTest.protoModel.Student.class, learnProto.practiceTest.protoModel.Student.Builder.class);
    }

    // Construct using learnProto.practiceTest.protoModel.Student.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (baseInfoBuilder_ == null) {
        baseInfo_ = null;
      } else {
        baseInfo_ = null;
        baseInfoBuilder_ = null;
      }
      calssId_ = 0;

      score_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return learnProto.practiceTest.protoModel.StudentModel.internal_static_prcticeProto_categories_Student_descriptor;
    }

    public learnProto.practiceTest.protoModel.Student getDefaultInstanceForType() {
      return learnProto.practiceTest.protoModel.Student.getDefaultInstance();
    }

    public learnProto.practiceTest.protoModel.Student build() {
      learnProto.practiceTest.protoModel.Student result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public learnProto.practiceTest.protoModel.Student buildPartial() {
      learnProto.practiceTest.protoModel.Student result = new learnProto.practiceTest.protoModel.Student(this);
      if (baseInfoBuilder_ == null) {
        result.baseInfo_ = baseInfo_;
      } else {
        result.baseInfo_ = baseInfoBuilder_.build();
      }
      result.calssId_ = calssId_;
      result.score_ = score_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof learnProto.practiceTest.protoModel.Student) {
        return mergeFrom((learnProto.practiceTest.protoModel.Student)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(learnProto.practiceTest.protoModel.Student other) {
      if (other == learnProto.practiceTest.protoModel.Student.getDefaultInstance()) return this;
      if (other.hasBaseInfo()) {
        mergeBaseInfo(other.getBaseInfo());
      }
      if (other.getCalssId() != 0) {
        setCalssId(other.getCalssId());
      }
      if (other.getScore() != 0) {
        setScore(other.getScore());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      learnProto.practiceTest.protoModel.Student parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (learnProto.practiceTest.protoModel.Student) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private learnProto.practiceTest.protoModel.Person baseInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        learnProto.practiceTest.protoModel.Person, learnProto.practiceTest.protoModel.Person.Builder, learnProto.practiceTest.protoModel.PersonOrBuilder> baseInfoBuilder_;
    /**
     * <code>.prcticeProto.base.Person baseInfo = 1;</code>
     */
    public boolean hasBaseInfo() {
      return baseInfoBuilder_ != null || baseInfo_ != null;
    }
    /**
     * <code>.prcticeProto.base.Person baseInfo = 1;</code>
     */
    public learnProto.practiceTest.protoModel.Person getBaseInfo() {
      if (baseInfoBuilder_ == null) {
        return baseInfo_ == null ? learnProto.practiceTest.protoModel.Person.getDefaultInstance() : baseInfo_;
      } else {
        return baseInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.prcticeProto.base.Person baseInfo = 1;</code>
     */
    public Builder setBaseInfo(learnProto.practiceTest.protoModel.Person value) {
      if (baseInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseInfo_ = value;
        onChanged();
      } else {
        baseInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.prcticeProto.base.Person baseInfo = 1;</code>
     */
    public Builder setBaseInfo(
        learnProto.practiceTest.protoModel.Person.Builder builderForValue) {
      if (baseInfoBuilder_ == null) {
        baseInfo_ = builderForValue.build();
        onChanged();
      } else {
        baseInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.prcticeProto.base.Person baseInfo = 1;</code>
     */
    public Builder mergeBaseInfo(learnProto.practiceTest.protoModel.Person value) {
      if (baseInfoBuilder_ == null) {
        if (baseInfo_ != null) {
          baseInfo_ =
            learnProto.practiceTest.protoModel.Person.newBuilder(baseInfo_).mergeFrom(value).buildPartial();
        } else {
          baseInfo_ = value;
        }
        onChanged();
      } else {
        baseInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.prcticeProto.base.Person baseInfo = 1;</code>
     */
    public Builder clearBaseInfo() {
      if (baseInfoBuilder_ == null) {
        baseInfo_ = null;
        onChanged();
      } else {
        baseInfo_ = null;
        baseInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.prcticeProto.base.Person baseInfo = 1;</code>
     */
    public learnProto.practiceTest.protoModel.Person.Builder getBaseInfoBuilder() {
      
      onChanged();
      return getBaseInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.prcticeProto.base.Person baseInfo = 1;</code>
     */
    public learnProto.practiceTest.protoModel.PersonOrBuilder getBaseInfoOrBuilder() {
      if (baseInfoBuilder_ != null) {
        return baseInfoBuilder_.getMessageOrBuilder();
      } else {
        return baseInfo_ == null ?
            learnProto.practiceTest.protoModel.Person.getDefaultInstance() : baseInfo_;
      }
    }
    /**
     * <code>.prcticeProto.base.Person baseInfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        learnProto.practiceTest.protoModel.Person, learnProto.practiceTest.protoModel.Person.Builder, learnProto.practiceTest.protoModel.PersonOrBuilder> 
        getBaseInfoFieldBuilder() {
      if (baseInfoBuilder_ == null) {
        baseInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            learnProto.practiceTest.protoModel.Person, learnProto.practiceTest.protoModel.Person.Builder, learnProto.practiceTest.protoModel.PersonOrBuilder>(
                getBaseInfo(),
                getParentForChildren(),
                isClean());
        baseInfo_ = null;
      }
      return baseInfoBuilder_;
    }

    private int calssId_ ;
    /**
     * <code>fixed32 calssId = 2;</code>
     */
    public int getCalssId() {
      return calssId_;
    }
    /**
     * <code>fixed32 calssId = 2;</code>
     */
    public Builder setCalssId(int value) {
      
      calssId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>fixed32 calssId = 2;</code>
     */
    public Builder clearCalssId() {
      
      calssId_ = 0;
      onChanged();
      return this;
    }

    private int score_ ;
    /**
     * <code>sint32 score = 3;</code>
     */
    public int getScore() {
      return score_;
    }
    /**
     * <code>sint32 score = 3;</code>
     */
    public Builder setScore(int value) {
      
      score_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 score = 3;</code>
     */
    public Builder clearScore() {
      
      score_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:prcticeProto.categories.Student)
  }

  // @@protoc_insertion_point(class_scope:prcticeProto.categories.Student)
  private static final learnProto.practiceTest.protoModel.Student DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new learnProto.practiceTest.protoModel.Student();
  }

  public static learnProto.practiceTest.protoModel.Student getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Student>
      PARSER = new com.google.protobuf.AbstractParser<Student>() {
    public Student parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Student> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Student> getParserForType() {
    return PARSER;
  }

  public learnProto.practiceTest.protoModel.Student getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

