// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: teacher.proto

package learnProto.practiceTest.protoModel;

public interface TeacherOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Teacher)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();
}
